---
name: EffechantForm
main: EffechantForm\Main
version: 1.0.5
api: 3.0.0
author: mixpowder
commands:
  ef:
    usage: /ef <help or enchant or effect or repair>
    description: エフェクト購入orエンチャント購入orアイテム修復
...
